
# important
#  - uses generic runTests.sh from uniolweb/unioltest (different paths !!!)

stages:
  - test
  - cleanup

test-job-static:
  tags:
    - typo3
    - shell
  stage: test
  script:
    - composer validate
    - composer lint
    - Build/Scripts/check_composer_lock_does_not_exist.sh
    - Build/Scripts/check_no_platform.php_exists_in_composer.json.sh

test-job-latest:
  tags:
    - typo3
    - shell
  stage: test
  script:
    - composer require typo3/cms-core:^13.4
    - composer cgl:check
    #- composer rector:check
    - .Build/vendor/uniolweb/unioltest/Build/Scripts/runTests.sh -p 8.4 -s phpstan
    - .Build/vendor/uniolweb/unioltest/Build/Scripts/runTests.sh -s unit -p 8.4

test-job-v12:
  tags:
    - typo3
    - shell
  stage: test
  script:
    - composer require typo3/cms-core:^12.4
    - composer rector:check
    - .Build/vendor/uniolweb/unioltest/Build/Scripts/runTests.sh -p 8.4 -s phpstan
    - .Build/vendor/uniolweb/unioltest/Build/Scripts/runTests.sh -s unit -p 8.4


test-job-info:
  tags:
    - typo3
    - shell
  stage: test
  script:
    - echo "Hello again you, $GITLAB_USER_LOGIN!"
    - who
    - pwd
    - hostname


#test-job-cleanup:
#  tags:
#    - typo3
#    - shell
#  stage: cleanup
#  script:
#    - cd Build/testing-docker
#    - docker compose down --remove-orphans
