# gitlab ci
#
# prerequisites:
# 1. Install runner, see https://docs.gitlab.com/runner/install/linux-repository.html
#   https://docs.gitlab.com/ee/ci/yaml/
#   runner is installed on wwwt304:
#   Show runners:
#    $ gitlab-runner list
# 2. register runner for group: gitlab-runner register --url ... --token
#    (token is shown in Settings CI/CD for group)
#

variables:
  PHP_PLATFORM_VERSION: "8.2.15"
  PHP_VERSION: "8.2"

test-job:
  tags:
    - typo3
    - shell
  stage: test
  script:
    - echo "Hello again you, $GITLAB_USER_LOGIN!"
    - who
    - pwd
    - hostname
    - composer validate
    - Build/Scripts/check_composer_lock_does_not_exist.sh
    - Build/Scripts/check_no_platform.php_exists_in_composer.json.sh
    - composer config platform.php "${PHP_PLATFORM_VERSION}"
    - if [ ! -f auth.json ] && [ ! -L auth.json ];then ln -s /home/gitlab-runner/private/auth.json auth.json;fi
    - composer install
    - echo "Start checking ..."
    - Build/Scripts/runTests.sh -s lint -p "${PHP_VERSION}"
    - Build/Scripts/runTests.sh -s composerValidate -p "${PHP_VERSION}"
    - Build/Scripts/runTests.sh -s cgl -n -p "${PHP_VERSION}"
    - Build/Scripts/runTests.sh -s phpstan -p "${PHP_VERSION}"
    - Build/Scripts/runTests.sh -s unit -p "${PHP_VERSION}"
    - composer config --unset platform.php
    - composer config --unset platform

