services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Uniolit\Bibtex\:
    resource: '../Classes/*'

  Uniolit\Bibtex\Service\Bibtex2Html\Bibtex2HtmlService:
    public: true

  Uniolit\Bibtex\Command\ConvertFlexformCommand:
    tags:
      - name: 'console.command'
        command: 'bibtex:convertFlexform'
        description: 'Convert Flexform'
        schedulable: false
        hidden: false

  Uniolit\Bibtex\Command\ConvertFlexform2Command:
    tags:
      - name: 'console.command'
        command: 'bibtex:convertFlexform2'
        description: 'Convert Flexform'
        schedulable: false
        hidden: false

  Uniolit\Bibtex\Command\DumpFlexformInfoCommand:
    tags:
      - name: 'console.command'
        command: 'bibtex:dumpFlexform'
        description: 'Dump Flexform information'
        schedulable: false
        hidden: false

  Uniolit\Bibtex\Command\CheckFlexformCommand:
    tags:
      - name: 'console.command'
        command: 'bibtex:checkFlexform'
        description: 'Check Flexform'
        schedulable: false
        hidden: false
