services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Uniolit\Bibtex\:
    resource: '../Classes/*'

  Uniolit\Bibtex\Service\Bibtex2Html\Bibtex2HtmlService:
    public: true

  Uniolit\Bibtex\Bibtex2Html\Service\FetchContent:
    public: true

  Uniolit\Bibtex\Backend\PreviewRenderer:
    public: true

  # cache
  # -----
  # Cache
  # -----
  #cache.bibtex:
  #  class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
  #  factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
  #  arguments: [ 'bibtex' ]

  #Uniolit\Bibtex\Cache\BibtexCache:
  #  arguments:
  #    $cache: '@cache.bibtex'
  #  public: true

  Uniolit\Bibtex\Cache\BibtexCache:
    public: true

  # commands
  # --------

  Uniolit\Bibtex\Command\ConvertFlexformCommand:
    tags:
      - name: 'console.command'
        command: 'bibtex:convertFlexform'
        description: 'Convert Flexform'
        schedulable: false
        hidden: false

  Uniolit\Bibtex\Command\ConvertFlexform2Command:
    tags:
      - name: 'console.command'
        command: 'bibtex:convertFlexform2'
        description: 'Convert Flexform'
        schedulable: false
        hidden: false

  Uniolit\Bibtex\Command\DumpFlexformInfoCommand:
    tags:
      - name: 'console.command'
        command: 'bibtex:dumpFlexform'
        description: 'Dump Flexform information'
        schedulable: false
        hidden: false

  Uniolit\Bibtex\Command\CheckFlexformCommand:
    tags:
      - name: 'console.command'
        command: 'bibtex:checkFlexform'
        description: 'Check Flexform'
        schedulable: false
        hidden: false
